---
- import_role:
    name: plans_standard
  when: multitenant or (not multitenant and address_space_type == "standard")
- import_role:
    name: plans_brokered
  when: multitenant or (not multitenant and address_space_type == "brokered")
- import_role:
    name: address_controller_singletenant
- import_role:
    name: none_authservice
  when: '"none" in authentication_services'
- import_role:
    name: standard_authservice
  when: '"standard" in authentication_services'
- import_role:
    name: address_controller
- import_role:
    name: service_catalog
  when: service_catalog
- import_role:
    name: api_server
  when: api_server
