---
- name: Create address space admin SA
  shell: oc create sa address-space-admin -n {{ namespace }}
  register: sa_exists
  failed_when: sa_exists.stderr != '' and 'already exists' not in sa_exists.stderr#
- name: Grant admin policy to address-space-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:address-space-admin -n {{ namespace }}
  #- name: Deploy default address space
  #  shell: oc process -f {{ playbook_dir }}/resources/templates/address-space.yaml NAME=default NAMESPACE={{ namespace }} TYPE={{ address_space_type }} PLAN={{ address_space_plan }} | oc apply -n {{ namespace }} -f -
