// Module included in the following assemblies:
//
// assembly-installing-manual-steps.adoc

include::common/attributes.adoc[]

[id='deploying-address-space-controller-{context}']
= Deploying the address space controller

The address space controller is responsible for creating the infrastructure used by address spaces.

NOTE: To install {ProductName} on {PlatformName} , you must have `cluster-admin` access to set up the required roles for creating namespaces and managing resources in those namespaces; otherwise, you are restricted to a single address space. For more information about how to deploy without `cluster-admin` access, which restricts {ProductName} to a single address space, see xref:deploying-single-namespace-{context}[].

.Procedure

. Create a service account for the {ProductName} address space controller:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} create sa enmasse-admin
----

. Install the default plan and resource configuration:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} create -f ./resources/resource-definitions/resource-definitions.yaml
{cmdcli} create -f ./resources/plans/standard-plans.yaml
{cmdcli} create -f ./resources/plans/brokered-plans.yaml
----

. Deploy the address space controller:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} create -f ./resources/address-space-controller/address-space-definitions.yaml
{cmdcli} create -f ./resources/address-space-controller/deployment.yaml
----

